{% set name = "gepetto-viewer-corba" %}
{% set version = "5.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Gepetto/gepetto-viewer-corba/releases/download/v{{ version }}/gepetto-viewer-corba-{{ version }}.tar.gz
  sha256: 79793619c55554be36b89ce348a0dd5bb84d6354363ca8b0ccc1bb2ffbae1f44

build:
  number: 3
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ cdt('mesa-libgl-devel') }}          # [linux]
    - {{ cdt('mesa-dri-drivers') }}          # [linux]
    - {{ cdt('libselinux-devel') }}          # [linux]
    - {{ cdt('libxdamage-devel') }}          # [linux]
    - {{ cdt('libx11-devel') }}              # [linux]
    - {{ cdt('libxfixes') }}                 # [linux]
    - {{ cdt('libxxf86vm') }}                # [linux]
    - {{ cdt('libxext') }}                   # [linux]
  host:
    - boost
    - boost-cpp
    - qt-main
    - openscenegraph
    - omniorb
    - omniorbpy
    - gepetto-viewer
    - python
  run:
    - omniorbpy
    - python

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/libgepetto-viewer-corba.so     # [linux]
    - test -f $PREFIX/lib/libgepetto-viewer-corba.dylib  # [osx]
  imports:
    - gepetto
    - gepetto.corbaserver

about:
  home: https://github.com/Gepetto/gepetto-viewer-corba
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Corba server for Gepetto (Graphical Interface for Pinocchio and hpp)
  description: |
    Corba server for Gepetto (Graphical Interface for Pinocchio and hpp)
  doc_url: https://gepettoweb.laas.fr/hpp/gepetto-viewer/doxygen-html/index.html
  dev_url: https://github.com/Gepetto/gepetto-viewer-corba

extra:
  recipe-maintainers:
    - ymontmarin
    - jcarpent
