{% set name = "gepetto-viewer-corba" %}
{% set version = "5.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Gepetto/gepetto-viewer-corba/releases/download/v{{ version }}/gepetto-viewer-corba-{{ version }}.tar.gz
  sha256: 308fc881740e8bfd363c1e162b4624f1859c289f7270721b5b908afcfd1eaf80

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
    - pkg-config
    - doxygen
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - omniorb                                # [build_platform != target_platform]
    - {{ cdt('mesa-libgl-devel') }}          # [linux]
    - {{ cdt('mesa-dri-drivers') }}          # [linux]
    - {{ cdt('libselinux-devel') }}          # [linux]
  host:
    - libboost-headers
    - qt-main
    - openscenegraph
    - omniorb
    - omniorbpy
    - gepetto-viewer
    - python
    - setuptools  # [py>311]
  run:
    - omniorbpy
    - python

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/libgepetto-viewer-corba.so     # [linux]
    - test -f $PREFIX/lib/libgepetto-viewer-corba.dylib  # [osx]
  imports:
    - gepetto
    - gepetto.corbaserver

about:
  home: https://github.com/Gepetto/gepetto-viewer-corba
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Corba server for Gepetto (Graphical Interface for Pinocchio and hpp)
  description: |
    Corba server for Gepetto (Graphical Interface for Pinocchio and hpp)
  doc_url: https://gepettoweb.laas.fr/hpp/gepetto-viewer/doxygen-html/index.html
  dev_url: https://github.com/Gepetto/gepetto-viewer-corba

extra:
  recipe-maintainers:
    - ymontmarin
    - jcarpent
